name: Build manylinux wheels, upload to PyPI upon release

# Update on when VERSION changes
on:
    push:
      branches:    
        - master
      paths:
        - 'VERSION'
    pull_request:
      branches:    
        - master
      paths:
        - 'VERSION'

jobs:
  build:
    name: Build manylinux wheels, upload to PyPI upon release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build manylinux2014_x86_64 wheels
        uses: ./.github/workflows/actions/manylinux2014_x86_64/
      - uses: actions/upload-artifact@v2-preview
        with:
          name: tensor-wheels-manylinux
          path: dist/*manylinux*.whl
      # Upload to PyPI if this is a release
      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: ${{ secrets.pypi_user }}
          password: ${{ secrets.pypi_pass }}
          packages_dir: dist/